exampleSite/config.toml
layouts/partials/head.html
layouts/partials/javascript.html

@rhazdon A lot of Hugo themes have this and I'd love this to be a feature

Add ability to add custom css and js

---

layouts/partials/head.html

removed the source code pro font, since you never used it in the theme

remove unused source code pro font

---

data/langFlags.yaml
i18n/es.toml

Went in and added support for spanish translation and it's corresponding flag. Just let me know if there are more files that depend on language and I can go in and translate them.

Added spanish support for flag and translation

---

data/langFlags.yaml
i18n/pt-br.toml

Hello Djordje,
I'm preparing my blog to use this theme, so I took the opportunity to add i18n support for pt-br (Português - Brasileiro).

Add translations and support for pt-br.

---

assets/scss/_main.scss

sass: fix h1 position

---

i18n/pt-br.toml

Fixing my mistake on copy and paste of French translation. Sorry about that.

Small fix on name of language

---

assets/scss/_logo.scss
assets/scss/_main.scss
assets/scss/_normalize.scss
assets/scss/_prism.scss

unfortunately wasn't my last patch enough.
So here are all missing font-display configurations
Signed-off-by: Christian Rebischke <chris@nullday.de>

added additional font-display configuration

---

.gitignore
assets/scss/_header.scss
layouts/partials/header.html

Fixed a bug that caused text to be highlighted after repeatedly clicking the 'theme-toggle' button.

 Fixed accidental text selection

---

README.md
exampleSite/config.toml
layouts/partials/svg.html

Added the [StackOverflow icon from Simple Icons](https://simpleicons.org/?q=stackoverflow).

Added Stackoverflow icon

---

data/langFlags.yaml
i18n/it.toml

This adds italian language to the theme.

i18n: add Italian

---

exampleSite/config.toml
layouts/partials/logo.html

Quick solution for #94, which adds a custom cursor logo animation duration or gives the option to remove the logo entirely. Animation can be disabled with an animation duration of `0s`.

Animation controls

---

layouts/partials/head.html

Pretty light, self-explanatory change.

add opengraph to head material

---

assets/scss/_main.scss
exampleSite/config.toml
layouts/index.html

I added an option for my site to add an image (e.g. portrait) on the front page.
I wanted just to share this here if you are interested.

Added option to add image (e.g. portrait) on front page

---

layouts/partials/sharingbuttons.html
layouts/posts/single.html

Allow to add custom add for post sharing, potential code to insert:
- http://hugocodex.org/add-ons/share-buttons/
- https://sharingbuttons.io/

Add sharing buttons

---

i18n/de.toml
i18n/en.toml
i18n/es.toml
i18n/fr.toml
i18n/hi.toml
i18n/it.toml
i18n/lmo.toml
i18n/ml.toml
i18n/pt-br.toml
i18n/ru.toml
i18n/tr.toml
layouts/posts/single.html

Add the date of the last modification to the line with the publish date

Add LastMod time in article info

---

data/langFlags.yaml
i18n/zh-hk.toml

As titled. Thanks for making this amazing theme!

Add support for Chinese (Hong Kong)/Cantonese (i18n)

---

layouts/partials/footer.html

Fix 215 and prevent extra bullet in footer if RSS is disabled

---

assets/scss/_tables.scss
assets/scss/main.scss

Hi! Thanks for this theme! It looks so good. I added some SCSS to make tables look pretty as well. You can check it out on my website here: https://www.alexday.me/projects/emoji/
If you have any suggestions I would be happy to add them.

Add CSS for tables to make them match the theme

---

assets/scss/_main.scss
exampleSite/config.toml
layouts/_default/baseof.html
layouts/index.html

Support for a background image **only** on the homepage.

added support for a background image on the homepage

---

docs/svgs.md

- link to gitbook's Simple Icons source
- fix lichess link
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rhazdon/hugo-theme-hello-friend-ng/257)

Minor fixes for SVG docs

---

layouts/partials/favicons.html

Resolves issue #326 
Reworked favicons partial for a better user experience.
I removed the config variable check and referenced the variables statically. This should require no change for current sites and should provide a better user experience for new users of the theme.

Reworked favicons partial for a better user experience

---

layouts/partials/head.html

see https://github.com/gohugoio/hugo/issues/9172

rm deprecated google_news internal template ref

---

assets/js/menu.js
exampleSite/config.toml
layouts/partials/logo.html

if the setting logoCursorPathname is setted to true, the logo text could be change.
the change will append the first url part of the host name.
some examples:

logo - append text according to current url path

---

exampleSite/config.toml
layouts/partials/head.html

Add support for plausible.io analytics

Add support for plausible.io

---

layouts/partials/footer.html

Set static copyright year

---

exampleSite/config.toml
layouts/_default/_markup/render-codeblock-mermaid.html
layouts/partials/javascript.html
layouts/posts/single.html

Hi,
I wanted to use https://utteranc.es for comments in my blog and saw that it wasn't supported yet. So here is the integration.
You can find it live on [my blog](https://rlemaitre.com/posts/)

Integrate utteranc.es comment system

---

layouts/partials/head.html

Update `.Site.GoogleAnalytics` to `.Site.Config.Services.GoogleAnalytics.ID`

Fix #483 - .Site.Config.Services.GoogleAnalytics.ID

---

README.md

For easy copying and pasting on terminal

Remove $ from bash code snippet

---

layouts/partials/head.html

Use toCSS alias.
Based upon https://gohugo.io/functions/css/sass/

Fix #482 - ToCSS

---

layouts/partials/footer.html

The author's name will be displayed correctly now.

Fix author not showing in footer
