- layouts/posts/single.html
Right now there wasn't an H1 at all, and the title was written out as a H2. Ideally we'd have the H1 be the main subject of the page (the post title seems appropriate for that), the first heading and there would be only the one H1.
> Updating to make post title it's H1 on single page

- assets/js/theme.js
- layouts/404.html
- layouts/_default/single.html
- layouts/partials/footer.html
- layouts/posts/single.html
I made two changes with this pull request:
- Replaced `absURL` with `absLangURL` so that viewers could be directed to pages in their languages.
- Set correct theme color meta once page is loaded. This fixes incorrect theme color (under mobile Chrome browser) when viewer set the page to non-default theme and then refresh the page.
> Better multilingual support

- layouts/partials/svg.html
Add a Telegram Icon to be displayed at social section. Although Feather
icons doesn't have any Telegram icon, I believe this is a good
replacement.
Also, have a look here: https://github.com/feathericons/feather/issues/58
> icons: add Telegram icon

- assets/scss/_logo.scss
Since the logo text wants to have the look and feel of a terminal, make the font `monospaced`.
The monospace word is used twice because of this hack:
https://stackoverflow.com/questions/38781089/font-family-monospace-monospace
> sass: make logo font monospaced

- assets/scss/_fonts.scss
font-display on `auto` makes sure that the text is always
visible for the user. It's a suggestion by Googles PageSpeed Insights
to activate this feature:
https://developers.google.com/web/updates/2016/02/font-display?utm_source=lighthouse&utm_medium=unknown
Signed-off-by: Christian Rebischke <chris@nullday.de>
> Added font-display: auto to _fonts.scss

- i18n/fr.toml
1. In the locale file for other languages, the language name is used instead of a nation's name.
https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/091ba7b1d2836ebf1defa1908020524174df6353/i18n/en.toml#L1
https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/091ba7b1d2836ebf1defa1908020524174df6353/i18n/es.toml#L1
https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/091ba7b1d2836ebf1defa1908020524174df6353/i18n/pt-br.toml#L1
2. A country doesn't represent a language.  For instance, an Austrian German speaker has imformed me of the differences between the language used in :austria: Austria and in :de: Germany.
3. The French lanugage (for numbers) differs across countries.
https://fr.wikipedia.org/wiki/Nombres_en_fran%C3%A7ais#France,_Canada_et_les_pays_d'Afrique_francopho …
> Changed i18n file comment heading

- assets/scss/_main.scss
Without flex-basis: auto, IE overlays the footer on top of long pages of text,
as its position seems to be computed relative to the initial viewport.
I haven't tested this thoroughly but it doesn't seem to affect modern FF, Chrome, or Edge, and fixes the issue in IE 11.
> Set container flex-basis to auto

- exampleSite/config.toml
- layouts/posts/single.html
I was thinking about using a variable like `showOtherPosts` in order to display the "Read Other Posts" section, but that would break backwards compatibility.
By setting `disableReadOtherPosts = true` that section will be hidden for all posts in the site.
> Added option to disable Read Other Posts

- layouts/partials/head.html
Instead of only using the keywords defined in the main config, also add the tags from posts to the keywords. For a bit more SEO.
> Add tags to keywords

- layouts/partials/head.html
If `.Description` parameter is given it's preferred over auto-generated `.Summary`
>  [SEO Optimization] Prioritize Description, Summary as fallback

- layouts/_default/list.html
Sections other than posts were displaying posts because it was hard coded in $contentTypeName.
> Fix section list pages

- layouts/_default/single.html
- layouts/posts/single.html
The internal templates (e.g., `_internal/twitter_cards.html`) have a divergent methodology for handling the cover images than the theme does. 
As currently structured the them is also quite opinionated that images are located in the `img` dir. Removing the `img/` in the cover allows for a more flexible positioning of image files in the static directory, but also (and for my purposes more importantly) allows me to DRY up my yaml front matter. 
For me, and I suspect most users, it would be most frequent that the cover image would also be the image we'd want in twitter cards and opengraph (facebook/linkedin) sharing. With the current system my front matter looks like this;
```yaml
cover: 2020/test.jpg
images: 
- img/2020/test.jpg
```
However with the minor (admittedly breaking) change below …
> Align how the theme handles cover images

- data/langFlags.yaml
- i18n/gl.toml
- layouts/partials/head.html
A PR containing:
- Translation (i18) for Galician language. (gl)
- Galician flag (es-ga) introduced in the last release of [lipis/flag-icon-css](https://github.com/lipis/flag-icon-css). ([Issue #405](https://github.com/lipis/flag-icon-css/pull/405)).
> Add Galician translation and flag

- layouts/partials/footer.html
This patch allows usage of `footerLeft` and `footerRight` params to override the bottom footer section. If not provided, the default is the previous static value.
Possibly could use better variable names, but the patch functions well on my demo page.
Supersedes #180 - apologies for second PR, wanted to move to a separate branch so other customizations don't affect this PR.
> Footer adjustable with Params

- layouts/_default/single.html
Use relURL instead of statically adding a / in front of the path.  
Otherwise, this would give issues with external URLs. Also assumes user would know that a / is added in front of the path, making it relative to the root.
> Use relURL for post-cover

- assets/scss/_menu.scss
When you refresh the page you need to wait for all the JavaScript to be loaded in order for the hamburger icon to disappear. This PR hides the icon in css when not on mobile.
> Fix hamburger icon flicker

- layouts/partials/logo.html
If the site is multilanguage, the logo link should redirect to the baseURL of the current language.
> Use relative lang URL

- README.md
Fixed a little typo that I found while reading, "linke" to "like".
> fixed typo "linke" to "like"

- assets/scss/_footer.scss
There is some unnecessary padding in the footer as shown here:
Note that this only occurs on the last-child on each line of the footer. This fix makes it even!
> Remove unnecessary padding in footer

- layouts/_default/single.html
- layouts/partials/tags.html
- layouts/posts/single.html
Just another quick change. So instead of hardcoding `.Params.tags` in `tags.html` we allow it to be reusable in different places. I'd like to render tags in my custom `list.html` view and it would be awesome to re-use the partial for theme default way of rendering tags.
> make tags partial reusable with different parameters

- README.md
Added example of social icons usage via `[[params.social]]` to README to increase clarity.
> Added Social Icons Example

- exampleSite/config.toml
- layouts/partials/footer.html
Hey everyone, 
I've been enjoying this theme for a while now and decided to contribute a bit more.
When customising the footer I noticed some odd behavior:
I wanted to remove the bottom half of the footer so configured the config.toml like so:
```
```
Because its empty It would default to the same lines again because of the way its coded in the footer.html.
When I configued something like " " it would also be weird because it would still treat it as text and show the span like so:
This PR introduces a footer config that has a few features:
- Optional trademark
- Optional RSS
- Optional copyright
- Optional author name
- Optional custom text
Any feedback is appreciated!
> Improve footer

- assets/scss/_single.scss
- layouts/posts/single.html
Just added an audio tag for blog posts, eg if someone wants to transcribe their blog post into an mp3 file and show it at the top of the page :slightly_smiling_face: 
On a post if you add the following
`audio: /test-file.mp3`
It will show the following: https://imgur.com/a/QViPMAO
Thanks for supporting this cool theme :+1:
> Added support for blog post audio.

- assets/scss/_404.scss
- assets/scss/main.scss
- layouts/404.html
This PR fixes some weird alignment issues on the icons on the 404 page.
It only makes an aesthetic change, so no site changes to configuration or site are needed.
Apologies for the different sized images, but here is a before and after:
**Before:**
**After:** 
If you want to see it in various browsers, it is deployed here: https://abyss.dev/404.html
> Improved alignment of icons on 404 page

- layouts/partials/head.html
- layouts/partials/javascript.html
Necessary for proof of ownership via Google Search Console
> layouts/partials: Move Google Analytics template into head

- assets/scss/_main.scss
The `<pre>` tag was set to a fixed background color that on the light
theme happened to be the same color of the text, making it impossible
to read.
This changes the background color to follow the theme setting using
the secondary light/dark color as background.
> Fix <pre> HTML tag to follow theme settings

- layouts/partials/svg.html
Icon downloaded from https://simpleicons.org/?q=patreon, with `<title>` tag removed and attributes rearranged to match other icons in svg.html.
> Add Patreon icon from Simple Icons

- layouts/partials/favicons.html
Fixes issue #358 by removing `meta` tag `theme-color` from the `favicons.html` file because it is added from the `head.html` partial.
> Removes duplicate meta theme-color

- layouts/partials/pagination-single.html
Fix rendering unneccessary box. It's visible when background color is changed or background is animated.
Empty box look like this on background:
> Fix unintentional render of empty box

- layouts/index.html
- layouts/partials/subtitle.html
Creating a separate partial allows users to customize the subtitle without overriding whole index file
> Make it easier to override subtitle

- layouts/partials/head.html
Follows up from #384 but also includes the subresource integrity value for the generated CSS bundle
> Include SRI for CSS assets

- layouts/partials/social-icons.html
This will add an attribute that will allow Mastodon users to get the ✅ on their profile when they add a mastodon social icon to their profile.
> Add rel=me for Mastodon verification

- assets/scss/_logo.scss
Logo text gets squeezed into very small area instead of taking place when a menu label is long. This commit fixes it by ensuring that it is not wrapped. This covers more cases and provides a good default for theme users.
Before:
After this fix:
> Fix squeezed logo text when menu title is long

- assets/scss/_list.scss
- layouts/_default/list.html
This commit changes targeted styling of `a` element to a class-based styling. This way, this is style is reusable on other elements and another `<a>` element can be used inside a `post-item`.
Otherwise, if someone would need to use `<a>` element in a post item, then he would get all other styles (such as `display:flex`) on every `<a>` which is unexpected.
This commit ensures that the style is abstracted from the element type itself, giving more flexibility when overriding the theme, and increases maintainability by making the intent more clear.
This would save from a potential fix like this:
To support scenarios like this:
> Improve styling to allow flexible overrides

- assets/js/main.js
If the theme is detected as dark, the first click on the toggle theme button will now change to light mode.
Preveously no change would occur, since it would switch from default dark to force dark mode.
> Fixed first time theme change from dark mode

- README.md
The readme mentions there being a setting to enable a global language menu, but doesn't show the setting itself.
> Add the global language switcher as a setting in the readme

- exampleSite/config.toml
Updated config.toml to avoid deprecation
Currently hugo show the following warning:
WARN  config: languages.en.subtitle: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.en.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
This pull  request aims to avoid problems in a future release.
> Hugo v112 deprecation warning

- i18n/de.toml
- i18n/en.toml
- i18n/es.toml
- i18n/fr.toml
- i18n/gl.toml
- i18n/id.toml
- i18n/it.toml
- i18n/ja.toml
- i18n/lmo.toml
- i18n/pt-br.toml
- i18n/ro.toml
- i18n/ru.toml
- i18n/tr.toml
- i18n/uk.toml
- i18n/zh-cn.toml
- layouts/partials/pagination-list.html
Adds missing translations for the strings `Newer posts` and `Older posts`. Those buttons are currently not translated.
Added the German and English translation and some others on "best effort basis" - native speakers should double-check it. Wasn't able to translate to some languages though.
Fixes issue #441
> Newer / older posts buttons not translated

- layouts/partials/social-icons.html
I've added a ``nonewpage`` parameter to social links to avoid popping them open on a new page. This is useful, for example, for adding an email page that is resistant to scraping.
As an example:
```
[[params.social]]
name = "email"
url  = "/email"
nonewpage = true
```
Where /email.md is a page that says something like
```
+++
title = 'Want to email me?'
+++
The address is ``this domain`` at ``this domain`` dot ``this tld``
```
> Add option to not open the socials link on a new page

- layouts/partials/head.html
This PR adds the possibility to set the `noindex` meta parameter in order to preventing search engine from indexing a particular post or page.
To enable it, the following line needs to be added to the front matter:
```yaml
noindex: true
```
Successfully tested on one of my websites.
> add noindex meta parameter

- layouts/posts/single.html
Update `.Site.DisqusShortname` to `.Site.Config.Services.Disqus.Shortname`
> Fix #484 - .Site.Config.Services.Disqus.Shortname

- layouts/partials/menu.html
Fixes #479 by sorting menu items by their "identifier parameter". I'm not experienced as a Hugo developer, so this may break things or need extra code (i.e: maybe a fallback if there is no identifier? or is identifier mandatory? idk)
> Make top menu order consistent across localizations.

- assets/scss/_fonts.scss
- layouts/index.html
When running a Google Pagespeed Insight test on a site with the hugo theme 2 things are flagged by google.
1. ` [aria-*] attributes are not valid or misspelled `
This comes from the fact that the main tag in html sets "aria-role" which is not a valid attribute.
I chose to delete this attribute since tagging it with the same name has no accessibility benefits.
2. ` Ensure text remains visible during webfont load `
This can be fixed by setting the font-display to swap.
The PR fixes both issues. This might be of value to other people trying to improve the google ranking.
> adding SEO improvements

- layouts/_default/list.html
Currently, the blog list dates are hardcoded to the `defaultContentLanguage` option, typically set to English. Consequently, regardless of the selected language, dates are always displayed in English.
This PR fixes this using the builtin function `time.Format`, which returns the date as formatted and <ins>localized</ins> string.
> Fix: Implement builtin localization for dates in blog list
